#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run format && npm run solhint && npm run lint 
npm run format && npm run solhint && npm run lint
npm run format && npm run solhint && npm run lint
npm run lint
